name: Build and Test

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build-and-test:

        name: build and test on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            # macos-13 is an intel runner, macos-14 is apple silicon
            # os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
            os: [windows-latest]

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
                cache: 'pip'

            - name : Install dependencies
              run: |
                pip install -r requirements.txt

            - name: Build
              run: |
                python setup.py build sdist bdist_wheel

            - name: Test
              run: |
                python setup.py test
                echo "Test passed"
