name: Build and Test

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build-and-test:
        name: build and test on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        
        strategy:
          matrix:
            # macos-13 is an intel runner, macos-14 is apple silicon
            # os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
            os: [windows-latest]

        defaults:
          run:
            shell: bash

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup python
              uses: actions/setup-python@v5
              id: setup-python
              with:
                python-version: '3.11'
                cache: 'pip'
            - name: Load cached Poetry installation
              uses: actions/cache@v4
              with:
                path: ~/.local
                key: poetry-1.8-${{ runner.os }}-${{ runner.arch }}-${{ steps.setup-python.outputs.python-version }}

            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                version: 1.8.5
                virtualenvs-create: true
                virtualenvs-in-project: true
                installer-parallel: true

            - name: Load cached venv
              uses: actions/cache@v4
              with:
                path: .venv
                key: venv-${{ runner.os }}-${{ runner.arch }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

            - name: Install dependencies
              run: poetry install --no-root --no-interaction

            - name: Build
              run: |
                ls -alrt .
                if [ "$RUNNER_OS" == "Windows" ]; then
                  # repeat the command until it succeeds
                  while ! poetry build; do sleep 1; done
                  poetry install --no-interaction
                else
                  poetry build && poetry install --no-interaction
                fi
                echo "Build done"
                ls -alR build

            - name: Test
              run: poetry run pytest

